"""
Backend — toolchain driver for the FoxFlow compiler.

Wraps the C++ backend (CMake + compiler) so the Julia driver can go
all the way from generated C++ sources to a running executable.

This keeps all orchestration in one place (instead of a bash script) so
FoxFlow can eventually be packaged as a single standalone `foxflow` binary.
"""
module Backend

export build_project, run_executable, find_executable, write_project_files, default_dggml_dir

# ---------------------------------------------------------------------------
# Self-contained CMake project generation
# ---------------------------------------------------------------------------

# CMake template for a standalone build of a generated FoxFlow model.
# Placeholders @FOXFLOW_DGGML_DIR@ and @TARGET@ are substituted at write time.
# A raw string is used so CMake's `${...}` syntax is not treated as Julia
# interpolation.
const CMAKELISTS_TEMPLATE = raw"""
# ===========================================================================
# Auto-generated by FoxFlow — self-contained CMake project for a model.
# Build:  cmake -S . -B build && cmake --build build -j
# Run:    ./build/<target> settings.json
#
# The FoxFlowDGGML library location defaults to the value baked in below.
# Override it with either:
#   cmake -S . -B build -DFOXFLOW_DGGML_DIR=/path/to/FoxFlowDGGML
# or the FOXFLOW_DGGML_DIR environment variable.
# ===========================================================================
cmake_minimum_required(VERSION 3.16)
project(FoxFlowModel VERSION 1.0 LANGUAGES CXX)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_definitions(-DCATCH_CONFIG_NO_POSIX_SIGNALS)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

option(ENABLE_SERIAL_HOST "Enable Serial Host Mode" ON)
if(ENABLE_SERIAL_HOST)
    add_definitions(-DDGGML_ENABLE_HOST_SERIAL)
endif()

# ---- FoxFlowDGGML library location ----
# Directory containing src/, dependencies/YAGL, thirdparty/{simdjson,vtu11}, tools/.
if(NOT DEFINED FOXFLOW_DGGML_DIR)
    if(DEFINED ENV{FOXFLOW_DGGML_DIR})
        set(FOXFLOW_DGGML_DIR "$ENV{FOXFLOW_DGGML_DIR}")
    else()
        set(FOXFLOW_DGGML_DIR "@FOXFLOW_DGGML_DIR@")
    endif()
endif()
if(NOT EXISTS "${FOXFLOW_DGGML_DIR}/src/CMakeLists.txt")
    message(FATAL_ERROR
        "FoxFlowDGGML library not found at FOXFLOW_DGGML_DIR='${FOXFLOW_DGGML_DIR}'.\n"
        "Set -DFOXFLOW_DGGML_DIR=/path/to/FoxFlowDGGML or the FOXFLOW_DGGML_DIR env var.")
endif()

# ---- SUNDIALS ----
find_package(SUNDIALS 6.7.0 QUIET)
if(NOT SUNDIALS_FOUND)
    message(STATUS "SUNDIALS 6.7.0 not found, fetching with FetchContent...")
    include(FetchContent)
    FetchContent_Declare(sundials
        GIT_REPOSITORY https://github.com/LLNL/sundials.git
        GIT_TAG v6.7.0 GIT_PROGRESS TRUE)
    FetchContent_MakeAvailable(sundials)
endif()

# ---- Cereal ----
find_package(Cereal QUIET)
if(NOT CEREAL_FOUND)
    message(STATUS "Cereal not found, fetching with FetchContent...")
    include(FetchContent)
    set(JUST_INSTALL_CEREAL ON CACHE BOOL "" FORCE)
    set(SKIP_PORTABILITY_TEST ON CACHE BOOL "" FORCE)
    set(SKIP_PERFORMANCE_COMPARISON ON CACHE BOOL "" FORCE)
    set(WITH_WERROR OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(cereal
        GIT_REPOSITORY https://github.com/USCiLab/cereal.git
        GIT_TAG v1.3.2)
    FetchContent_MakeAvailable(cereal)
endif()

# ---- LibTorch ----
find_package(Torch QUIET)
if(NOT Torch_FOUND)
    message(STATUS "LibTorch not found, fetching (this may take several minutes)...")
    include(FetchContent)
    set(LIBTORCH_URL
        https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.2.0%2Bcpu.zip)
    FetchContent_Declare(libtorch URL ${LIBTORCH_URL})
    FetchContent_MakeAvailable(libtorch)
    set(Torch_DIR ${libtorch_SOURCE_DIR}/share/cmake/Torch CACHE PATH "" FORCE)
    find_package(Torch REQUIRED)
endif()

# ---- DGGML include paths ----
include_directories(${FOXFLOW_DGGML_DIR}/dependencies/YAGL/include)
include_directories(${FOXFLOW_DGGML_DIR}/thirdparty/simdjson)
include_directories(${FOXFLOW_DGGML_DIR}/src)
include_directories(${FOXFLOW_DGGML_DIR}/src/Listeners)
include_directories(${FOXFLOW_DGGML_DIR}/src/Grids)
include_directories(${FOXFLOW_DGGML_DIR}/src/Utlities)
include_directories(${FOXFLOW_DGGML_DIR}/src/Grammar)
include_directories(${FOXFLOW_DGGML_DIR}/src/CellComplexes)
include_directories(${FOXFLOW_DGGML_DIR}/src/CellComplexes/Utils)
include_directories(${FOXFLOW_DGGML_DIR}/src/Solvers)

# ---- DGGML subprojects (external source dirs require explicit binary dirs) ----
add_subdirectory(${FOXFLOW_DGGML_DIR}/dependencies/YAGL  ${CMAKE_BINARY_DIR}/_foxflow/YAGL)
add_subdirectory(${FOXFLOW_DGGML_DIR}/thirdparty/vtu11   ${CMAKE_BINARY_DIR}/_foxflow/vtu11)
add_subdirectory(${FOXFLOW_DGGML_DIR}/src               ${CMAKE_BINARY_DIR}/_foxflow/DGGML_src)
add_subdirectory(${FOXFLOW_DGGML_DIR}/tools             ${CMAKE_BINARY_DIR}/_foxflow/DGGML_tools)

# ---- The generated model ----
configure_file("settings.json" "settings.json" COPYONLY)

add_executable(@TARGET@ main.cpp ${FOXFLOW_DGGML_DIR}/thirdparty/simdjson/simdjson.cpp)
target_link_libraries(@TARGET@ PRIVATE vtu11::vtu11)
target_link_libraries(@TARGET@ PUBLIC SUNDIALS::arkode SUNDIALS::nvecserial)
target_link_libraries(@TARGET@ PRIVATE cereal::cereal)
target_link_libraries(@TARGET@ PRIVATE torch)
target_compile_features(@TARGET@ PRIVATE cxx_std_17)
"""

"""
    default_dggml_dir() -> String

Best-effort default location of the FoxFlowDGGML library shipped with this
repository, computed relative to this source file. Overridable at build time
via `-DFOXFLOW_DGGML_DIR` or the `FOXFLOW_DGGML_DIR` env var.
"""
function default_dggml_dir()
    repo = normpath(joinpath(@__DIR__, "..", ".."))
    return joinpath(repo, "src", "tests", "generated_tests", "include",
                    "FoxFlowDGGML3D", "FoxFlowDGGML")
end

"""
    write_project_files(output_dir; dggml_dir=default_dggml_dir(), target="main")

Write a self-contained `CMakeLists.txt` (and an empty `settings.json` if one is
missing) into `output_dir`, so the generated model can be built on its own with
`cmake -S output_dir -B build`.
"""
function write_project_files(output_dir::AbstractString;
                             dggml_dir::AbstractString=default_dggml_dir(),
                             target::AbstractString="main")
    mkpath(output_dir)

    content = replace(CMAKELISTS_TEMPLATE,
                      "@FOXFLOW_DGGML_DIR@" => dggml_dir,
                      "@TARGET@" => target)
    open(joinpath(output_dir, "CMakeLists.txt"), "w") do io
        write(io, content)
    end

    # The model CLI requires a JSON argument and CMake copies settings.json
    # next to the binary; provide a placeholder if the user hasn't supplied one.
    settings = joinpath(output_dir, "settings.json")
    if !isfile(settings)
        open(settings, "w") do io
            write(io, "{}\n")
        end
    end
    println("[backend] Wrote self-contained CMakeLists.txt (FOXFLOW_DGGML_DIR=$dggml_dir)")
    return output_dir
end

# ---------------------------------------------------------------------------
# CMake build + run
# ---------------------------------------------------------------------------

"""
    build_project(project_dir; kwargs...) -> build_dir

Configure and compile a CMake project.

# Arguments
- `project_dir`: directory containing the top-level `CMakeLists.txt`.

# Keywords
- `build_dir`:    out-of-source build directory (default: `<project_dir>/build`).
- `target`:       CMake target to build (default: `nothing` = build all).
- `sundials_dir`: passed as `-DSUNDIALS_DIR` when non-empty
                  (default: `ENV["FOXFLOW_SUNDIALS_DIR"]` if set).
- `cmake`:        cmake executable (default: `ENV["FOXFLOW_CMAKE"]` or `"cmake"`).
- `jobs`:         parallel build jobs (default: number of CPU threads).

Returns the build directory.
"""
function build_project(project_dir::AbstractString;
                       build_dir::AbstractString=joinpath(project_dir, "build"),
                       target::Union{Nothing,AbstractString}=nothing,
                       sundials_dir::AbstractString=get(ENV, "FOXFLOW_SUNDIALS_DIR", ""),
                       cmake::AbstractString=get(ENV, "FOXFLOW_CMAKE", "cmake"),
                       jobs::Integer=Sys.CPU_THREADS)

    isdir(project_dir) || error("CMake project directory not found: $project_dir")
    isfile(joinpath(project_dir, "CMakeLists.txt")) ||
        error("No CMakeLists.txt in project directory: $project_dir")

    mkpath(build_dir)

    # ---- Configure ----
    configure = `$cmake -S $project_dir -B $build_dir`
    if !isempty(sundials_dir)
        configure = `$configure -DSUNDIALS_DIR=$sundials_dir`
    end
    println("[backend] Configuring: ", configure)
    run(configure)

    # ---- Build ----
    build = `$cmake --build $build_dir -j $jobs`
    if target !== nothing
        build = `$cmake --build $build_dir --target $target -j $jobs`
    end
    println("[backend] Building: ", build)
    run(build)

    return build_dir
end

"""
    find_executable(build_dir, name) -> path or nothing

Search `build_dir` recursively for an executable file named `name`.
CMake mirrors the source subdirectory layout, so the binary location is
not always predictable; walking the tree is the most robust approach.
"""
function find_executable(build_dir::AbstractString, name::AbstractString)
    for (root, _dirs, files) in walkdir(build_dir)
        for f in files
            f == name || continue
            p = joinpath(root, f)
            isfile(p) || continue
            if Sys.iswindows() || (filemode(p) & 0o111) != 0
                return p
            end
        end
    end
    return nothing
end

"""
    run_executable(exe; args=String[], dir=dirname(exe), wait=true)

Run a built executable from working directory `dir` (defaults to the
executable's directory, where CMake copies `settings.json`).

When `wait=true` (default) this blocks until the process exits. When
`wait=false` it returns the running `Process` immediately so the caller can do
other work (e.g. drive a file watcher) while the simulation runs.
"""
function run_executable(exe::AbstractString; args::AbstractVector=String[],
                        dir::AbstractString=dirname(exe), wait::Bool=true)
    isfile(exe) || error("Executable not found: $exe (did the build succeed?)")
    # Resolve to absolute paths: `dir` becomes the child's cwd, so a relative
    # `exe` (e.g. from a relative output_dir) would otherwise be resolved
    # against `dir` and fail to spawn (ENOENT).
    exe = abspath(exe)
    dir = abspath(dir)
    println("[backend] Running: ", exe, "  (cwd: ", dir, ")")
    proc = run(Cmd(`$exe $args`, dir=dir); wait=wait)
    return wait ? nothing : proc
end

end # module Backend
